name: harry_potter
description: "Demo app for CIFO Flutter course"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.3.2
  isar_community: 3.3.0-dev.3
  isar_community_flutter_libs: 3.3.0-dev.3
  path_provider: ^2.1.5
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  isar_community_generator: 3.3.0-dev.3
  build_runner: ^2.7.1

dependency_overrides:
  analyzer: 8.3.0

flutter:
  uses-material-design: true